name: OPM Reference Manual CI

# NOTE: Added "push" here such that PR authors can test the actions in their forked repository
# before submitting a PR.
# NOTE: It is not possible to avoid the duplication of the paths in the "push" and
# "pull_request" sections. This is a known limitation of the GitHub Actions syntax.
on:
    push:
      paths:
        - 'scripts/python/**'
        - '.github/workflows/ci.yml'
    pull_request:
      paths:
        - 'scripts/python/**'
        - '.github/workflows/ci.yml'

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [ubuntu-latest, macos-latest, windows-latest]
            python-version: ["3.10", "3.11"]
    steps:
      - name: checkout source code
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
      - name: Install dependencies
        run: |
          cd scripts/python
          poetry install
      - name: Run tests
        run: |
          cd scripts/python
          poetry run pytest tests
